pipeline{

	agent any

	environment {
		DOCKERHUB_CREDENTIALS=credentials('elefanti60_pipeline')
	}

	stages {

		stage('Build') {

			steps {
				sh 'docker build -t drensokoli/elefanti60:tagname .'
			}
		}

		stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Push') {

			steps {
				sh 'docker push drensokoli/elefanti60:tagname'
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
	}

}